language: go
go:
  - "1.x"

env:
  - DEP_VERSION="0.5.0"

before_install:
  # Install dep
  - - if [[ "${TRAVIS_CPU_ARCH}" == "ppc64le" ]]; then curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-ppc64le -o $GOPATH/bin/dep; else curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep; fi
  - chmod +x $GOPATH/bin/dep

  # Install golint
  - go get golang.org/x/lint/golint

arch:
  - amd64
  - ppc64le


